"""add asset registry: product models, physical units, functional locations

Revision ID: 01847c2561a1
Revises: 5929036bce23
Create Date: 2026-09-22 11:22:46.005741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01847c2561a1'
down_revision: Union[str, None] = '5929036bce23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['functional_locations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_model_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_location_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('functional_location_id', sa.UUID(), nullable=False),
    sa.Column('physical_unit_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['functional_location_id'], ['functional_locations.id'], ),
    sa.ForeignKeyConstraint(['physical_unit_id'], ['physical_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # (l'index audit_log_tenant_seq_idx n'est pas déclaré au niveau du
    # modèle ORM, donc l'autogénération le voit à tort comme supprimé ;
    # on ne touche pas à audit_log ici.)

    # Un seul exemplaire physique peut occuper une position fonctionnelle à
    # un instant donné : l'index partiel l'impose au niveau base de données.
    op.create_index(
        'functional_location_one_open_assignment',
        'functional_location_assignments',
        ['functional_location_id'],
        unique=True,
        postgresql_where=sa.text('valid_to IS NULL'),
    )
    op.create_index(
        'physical_units_tenant_serial_idx',
        'physical_units',
        ['tenant_id', 'serial_number'],
        unique=True,
    )

    for table in ('product_models', 'physical_units', 'functional_locations', 'functional_location_assignments'):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ('functional_location_assignments', 'functional_locations', 'physical_units', 'product_models'):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    op.drop_index('physical_units_tenant_serial_idx', table_name='physical_units')
    op.drop_index(
        'functional_location_one_open_assignment',
        table_name='functional_location_assignments',
        postgresql_where=sa.text('valid_to IS NULL'),
    )
    op.drop_table('functional_location_assignments')
    op.drop_table('physical_units')
    op.drop_table('functional_locations')
    op.drop_table('product_models')
    # ### end Alembic commands ###
